### ISSUE TITLE
Error: [ERROR] terraform-provider-alicloud/alicloud/resource_alicloud_oss_bucket.go:318: Resource alicloud_oss_bucket IsBucketExist Failed!!!

### ISSUE THREAD

**Issue by ynorvo** [aliyun/terraform-provider-alicloud#2824]
Hi there,

Thank you for opening an issue. Please note that we try to keep the Terraform issue tracker reserved for bug reports and feature requests. For general usage questions, please see: https://www.terraform.io/community.html.

### Terraform Version
Terraform v0.12.29
+ provider.alicloud v1.96.0

### Affected Resource(s)
alicloud_oss_bucket

### Expected Behavior
module.oss1.alicloud_oss_bucket.bucket-new: Creating...
module.oss1.alicloud_oss_bucket.bucket-new: Creation complete after 4s [id=conweb-qas-terraform-bucket-test]

Warning: Interpolation-only expressions are deprecated

  on ../../../../tf_modules_aliyun/tf_module_aliyun_oss/main.tf line 11, in resource "alicloud_oss_bucket" "bucket-new":
  11:   bucket = "${var.bucket-new}"

Terraform 0.11 and earlier required all non-constant expressions to be
provided via interpolation syntax, but this pattern is now deprecated. To
silence this warning, remove the "${ sequence from the start and the }"
sequence from the end of this expression, leaving just the inner expression.

Template interpolation syntax is still used to construct strings from
expressions when the template includes multiple interpolation sequences or a
mixture of literal strings and interpolations. This deprecation applies only
to templates that consist entirely of a single interpolation sequence.

(and 3 more similar warnings elsewhere)

Apply complete! Resources: 1 added, 0 changed, 0 destroyed.

### Actual Behavior
Error as the below:
module.oss1.alicloud_oss_bucket.bucket-new: Creating...

Warning: Interpolation-only expressions are deprecated

  on ../../../../tf_modules_aliyun/tf_module_aliyun_oss/main.tf line 11, in resource "alicloud_oss_bucket" "bucket-new":
  11:   bucket = "${var.bucket-new}"

Terraform 0.11 and earlier required all non-constant expressions to be
provided via interpolation syntax, but this pattern is now deprecated. To
silence this warning, remove the "${ sequence from the start and the }"
sequence from the end of this expression, leaving just the inner expression.

Template interpolation syntax is still used to construct strings from
expressions when the template includes multiple interpolation sequences or a
mixture of literal strings and interpolations. This deprecation applies only
to templates that consist entirely of a single interpolation sequence.

(and 3 more similar warnings elsewhere)

#### Get "http://HTTPS:/?max-keys=1&prefix=qas-terraform-bucket-test": dial tcp: lookup HTTPS on 10.10.10.10:53: server misbehaving

  on ../../../../tf_modules_aliyun/tf_module_aliyun_oss/main.tf line 10, in resource "alicloud_oss_bucket" "bucket-new":
  10: resource "alicloud_oss_bucket" "bucket-new" {

### Steps to Reproduce
terraform apply

PS:
Terraform apply successfully in provide.alicloud v1.95.0, issue started from v1.96.0.

**Comment by xiaozhu36** [comment]
Hi @ynorvo I am sorry for the issue and it has been fixed by #2811 . The next release will fix it.

**Comment by roura356a** [comment]
Same here, hopefully next release is soon, this is stopping all my client's new infrastructure.

**Comment by roura356a** [comment]
Hi, when is the next release scheduled? This issue is stopping creating the resources for my client's new alicloud account.

**Comment by xiaozhu36** [comment]
@roura356a The next release has been published and please update it to version 1.97.0 to fix this issue.

**Comment by roura356a** [comment]
Thank you so much @xiaozhu36!!

**Comment by raiz-manjur** [comment]
Hi i am using Provider 1.97.0 
issue still exists
Error: [ERROR] terraform-provider-alicloud/alicloud/resource_alicloud_oss_bucket.go:318: Resource alicloud_oss_bucket **IsBucketExist** Failed!!! [SDK aliyun-oss-go-sdk ERROR]:
There is no any available endpoint for oss in region ap-southeast-5.

TRACE_LOG: 
`alicloud_oss_bucket.assets1: Still creating... [10s elapsed]
2020/11/04 12:21:12 [DEBUG] alicloud_oss_bucket.assets1: apply errored, but we're indicating that via the Error pointer rather than returning it: [ERROR] terraform-provider-alicloud/alicloud/resource_alicloud_oss_bucket.go:318: Resource alicloud_oss_bucket IsBucketExist Failed!!! [SDK aliyun-oss-go-sdk ERROR]:
There is no any available endpoint for oss in region ap-southeast-5.
2020/11/04 12:21:12 [TRACE] <root>: eval: *terraform.EvalMaybeTainted
2020/11/04 12:21:12 [TRACE] EvalMaybeTainted: alicloud_oss_bucket.assets1 encountered an error during creation, so it is now marked as tainted
2020/11/04 12:21:12 [TRACE] <root>: eval: *terraform.EvalWriteState
2020/11/04 12:21:12 [ERROR] <root>: eval: *terraform.EvalSequence, err: [ERROR] terraform-provider-alicloud/alicloud/resource_alicloud_oss_bucket.go:318: Resource alicloud_oss_bucket IsBucketExist Failed!!! [SDK aliyun-oss-go-sdk ERROR]:
There is no any available endpoint for oss in region ap-southeast-5.
2020/11/04 12:21:12 [TRACE] [walkApply] Exiting eval tree: alicloud_oss_bucket.assets1
2020/11/04 12:21:12 [TRACE] vertex "alicloud_oss_bucket.assets1": visit complete`

**Comment by manzurshaikh** [comment]
Hi i am using Provider 1.97.0 
issue still exists
Error: [ERROR] terraform-provider-alicloud/alicloud/resource_alicloud_oss_bucket.go:318: Resource alicloud_oss_bucket **IsBucketExist** Failed!!! [SDK aliyun-oss-go-sdk ERROR]:
There is no any available endpoint for oss in region ap-southeast-5.

TRACE_LOG: 
`alicloud_oss_bucket.assets1: Still creating... [10s elapsed]
2020/11/04 12:21:12 [DEBUG] alicloud_oss_bucket.assets1: apply errored, but we're indicating that via the Error pointer rather than returning it: [ERROR] terraform-provider-alicloud/alicloud/resource_alicloud_oss_bucket.go:318: Resource alicloud_oss_bucket IsBucketExist Failed!!! [SDK aliyun-oss-go-sdk ERROR]:
There is no any available endpoint for oss in region ap-southeast-5.
2020/11/04 12:21:12 [TRACE] <root>: eval: *terraform.EvalMaybeTainted
2020/11/04 12:21:12 [TRACE] EvalMaybeTainted: alicloud_oss_bucket.assets1 encountered an error during creation, so it is now marked as tainted
2020/11/04 12:21:12 [TRACE] <root>: eval: *terraform.EvalWriteState
2020/11/04 12:21:12 [ERROR] <root>: eval: *terraform.EvalSequence, err: [ERROR] terraform-provider-alicloud/alicloud/resource_alicloud_oss_bucket.go:318: Resource alicloud_oss_bucket IsBucketExist Failed!!! [SDK aliyun-oss-go-sdk ERROR]:
There is no any available endpoint for oss in region ap-southeast-5.
2020/11/04 12:21:12 [TRACE] [walkApply] Exiting eval tree: alicloud_oss_bucket.assets1
2020/11/04 12:21:12 [TRACE] vertex "alicloud_oss_bucket.assets1": visit complete`
