### ISSUE TITLE
Unable to create `resource_alicloud_gpdb_instance` ErrorCode: COMMODITY.INVALID_COMPONENT Message: 模块非法

### ISSUE THREAD

**Issue by hayorov** [aliyun/terraform-provider-alicloud#3802]
Hi there,

### Terraform Version
Terraform v1.0.3
on darwin_amd64

### Affected Resource(s)
- resource_alicloud_gpdb_instance

### Terraform Configuration Files
```hcl
resource "alicloud_gpdb_instance" "example" {
  description          = "test-db-l3"
  engine               = "gpdb"
  engine_version       = "4.3"
  instance_class       = "gpdb.group.segsdx2"
  instance_group_count = "2"
  vswitch_id           = <some-vswitch-id>
  security_ip_list     = ["10.168.1.12", ]
  instance_charge_type = "PostPaid"
}
```

### Debug Output
```
Plan: 1 to add, 0 to change, 0 to destroy.
alicloud_gpdb_instance.example: Creating...

Error: [ERROR] terraform-provider-alicloud/alicloud/resource_alicloud_gpdb_instance.go:146: Resource alicloud_gpdb_instance CreateDBInstance Failed!!! [SDK alibaba-cloud-sdk-go ERROR]:
SDK.ServerError
ErrorCode: COMMODITY.INVALID_COMPONENT
Recommend: https://error-center.aliyun.com/status/search?Keyword=COMMODITY.INVALID_COMPONENT&source=PopGw
RequestId: 1392C14F-511F-5194-91DD-D3DDDFBD5051
Message: 模块非法

  with alicloud_gpdb_instance.example,
  on main.tf line 1, in resource "alicloud_gpdb_instance" "example":
   1: resource "alicloud_gpdb_instance" "example" {
```

### Expected Behavior
Resource provisioning

### Actual Behavior
ErrorCode: COMMODITY.INVALID_COMPONENT Message: 模块非法

### Steps to Reproduce
1. `terraform apply`

### Additional info
provider alicloud v1.129.0
region Singapore
zone A

**Comment by tiankai66** [comment]
Your feedback has been received. We will process it as soon as possible.
Thank you for your trust and support of Alibaba Cloud!

**Comment by hayorov** [comment]
Hello 👋  any updates?

**Comment by tiankai66** [comment]
Hello, sorry for reply late. some updates for you:
As the notes in "https://registry.terraform.io/providers/aliyun/alicloud/latest/docs/resources/gpdb_instance"
This resource is used to manage a Reserved Storage Mode instance, and creating a new reserved storage mode instance is no longer supported since v1.127.0. You can still use this resource to manage the instance which has been already created, but can not create a new one.
create new resource can use the following:
https://registry.terraform.io/providers/aliyun/alicloud/latest/docs/resources/gpdb_elastic_instance

**Comment by hayorov** [comment]
Many thanks, @tiankai66 I'll try `elastic` resource instead.
